accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up/', views.sign_up, name='sign_up'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

flover/urls.py
from django.contrib import admin
from django.urls import path, include
from posts import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('intro/', include('intro.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    

intro/urls.py
from django.urls import path
from . import views

app_name = 'intro'
urlpatterns = [
    path('', views.index, name='index'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('list_check/', views.list_check, name = 'list_check'),
    path('search/', views.search, name = 'search'),
    path('search_result/', views.search_result, name = 'search_result')
]

accounts/models.py
from django.db import models

# Create your models here.

intro/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    def __str__(self):
        if self.user:
            return f'{self.user.get_username()}: {self.body}'

        return f'{self.body}'

posts/models.py
from django.db import models

# Create your models here.
class Keyword(models.Model):
    name = models.CharField(max_length = 20)    

    def __str__(self):
        return f"name : {self.name}"

class FlowerColor(models.Model):
    name = models.CharField(max_length = 20)    

    def __str__(self):
        return f"name : {self.name}"


class FlowerType(models.Model):
    name = models.CharField(max_length = 20)    

    def __str__(self):
        return f"name : {self.name}"


class Item(models.Model):
    name = models.CharField(max_length = 100, null=True)
    info = models.TextField()
    image = models.ImageField(upload_to = 'posts', null = True)
    tagged_keywords = models.ManyToManyField(Keyword, related_name = 'flower_list')
    tagged_colors = models.ManyToManyField(FlowerColor, related_name = 'flower_list')
    tagged_types = models.ManyToManyField(FlowerType, related_name = 'flower_list')
    
    def __str__(self):
        return f"name : {self.name} | info : {self.info}"    

class Shop(models.Model):
    name = models.CharField(max_length = 100)
    location = models.TextField()
    phone = models.IntegerField(null=True)

    def __str__(self):
        return f"name : {self.name} | info : {self.location} | phone: {self.phone}"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.


def sign_up(request):
    context = {}

    # POST Method
    if request.method == 'POST':
        if (request.POST['username'] and
                request.POST['password'] and
                request.POST['password'] == request.POST['password_check']):

            new_user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password'],
            )

            auth.login(request, new_user)
            return redirect('posts:index')

        else:
            context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

    # GET Method
    return render(request, 'accounts/sign_up.html', context)


def login(request):
    context = {}

    # POST Method
    if request.method == 'POST':
        if request.POST['username'] and request.POST['password']:

            user = auth.authenticate(
                request,
                username=request.POST['username'],
                password=request.POST['password']
            )

            if user is not None:
                auth.login(request, user)
                return redirect('posts:index')
            else:
                context['error'] = '아이디와 비밀번호를 다시 확인해주세요.'

        else:
            context['error'] = '아이디와 비밀번호를 모두 입력해주세요.'

    # GET Method
    return render(request, 'accounts/login.html', context)


def logout(request):
    if request.method == 'POST':
        auth.logout(request)

    return redirect('posts:index')

intro/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.

def index(request):
    return render(request, 'intro/index.html')

posts/views.py
from django.shortcuts import render
from .models import Item, Keyword, FlowerType, FlowerColor


# Create your views here.

def index(request):
    items = Item.objects.all()
    context = {'items': items}
    return render(request, 'posts/index.html', context)

def list_check(request):
    items = Item.objects.all()
    context = {'items': items}

    return render(request, 'posts/list_check.html', context)

def search(request):
    keywords = Keyword.objects.all()
    flowercolors = FlowerColor.objects.all()
    flowertypes = FlowerType.objects.all()
    context = {'keywords': keywords,'flowercolors':flowercolors,'flowertypes':flowertypes }

    return render(request, 'posts/search.html', context)


def search_result(request):
    keyword_op = request.POST.getlist('keyword_op')
    flowercolor_op = request.POST.getlist('flowercolor_op')
    flowertype_op = request.POST.getlist('flowertype_op')

    items = Item.objects.all()

    context = {'items': items, 'keyword_op': keyword_op, 'flowercolor_op': flowercolor_op, 'flowertype_op':flowertype_op}
    return render(request, 'posts/search_result.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
    {% endif %}

    <form action="{% url 'accounts:login' %}" method="POST">
      {% csrf_token %}

      <h1>Login</h1>

      <div class="form-group">
        <label for="username">아이디</label>
        <input type="text" id="username" name="username" placeholder="아이디">
      </div>

      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" id="password" name="password" placeholder="비밀번호">
      </div>

      <button type="submit" class="btn btn-primary">로그인</button>
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    {% if error %}
      <div class="alert alert-danger" role="alert">
        {{ error }}
      </div>
    {% endif %}

    <form action="{% url 'accounts:sign_up' %}" method="POST">
      {% csrf_token %}

      <h1>Sign Up</h1>

      <div class="form-group">
        <label for="username">아이디</label>
        <input type="text" id="username" name="username" placeholder="아이디">
      </div>

      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" id="password" name="password" placeholder="비밀번호">
      </div>

      <div class="form-group">
        <label for="password_check">비밀번호 확인</label>
        <input type="password" id="password_check" name="password_check" placeholder="비밀번호 확인">
      </div>

      <button type="submit" class="btn btn-primary">회원가입</button>
    </form>
  </div>
{% endblock %}

intro/templates/intro/index.html
{% load static %}

<!doctype html>
<html lang="ko">
  <head>
  <meta charset="utf-8">
    <title>Flover</title>
    <style>
      body { padding: 0px; margin: 0px; }
      .jb-box { width: 100%; height: 500px; overflow: hidden;margin: 0px auto; position: relative; }
      video { width: 100%; }
      .jb-text { position: absolute; top: 50%; width: 100%; }
      .jb-text p { margin-top: -24px; text-align: center; font-size: 48px; color: #ffffff; }
    </style>
  </head>
  <body>
    <div class="jb-box">
      <video muted autoplay loop>
        <source src="{% static 'video/intro.mp4' %}" type="video/mp4">
        <strong>Your browser does not support the video tag.</strong>
      </video>
      <div class="jb-text">
        <p>Choose your flower, I'll be your lover</p>
      </div>
    </div>
  
  <head>
  <style type="text/css">
  
  p{
  text-align: center;
  }
  img
  {
  border: 3px;
  width: 200px;
  height: 100px;
  }
</style>
</head>

<body>
<p>


<a href="http://127.0.0.1:8000/posts/" height="5" width="10" target="_blank">
  <img src="{% static 'intro/image/mainlogo.jpg' %}" type="img/jpg">
<a>


</p>

</body>
</html>

posts/templates/posts/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}

{% endblock %}

{% block content %}

<img src="{% static 'posts/main.jpg' %}" alt="이미지 링크 잘못됐다">


<p> 뭐지 왜...</p>

<div class="p-3 mb-2 bg-info text-white"> FLOWER LIST </div>
<div class="card-deck">
    {% for item in items %}

    <div class="card">
      <img src="{{item.image.url}}" class="card-img-top rounded" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{item.name}}</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

posts/templates/posts/list_check.html
{% extends "base.html" %}
{% load static %}
{% block style %}

{% endblock %}

{% block content %}
    <h1> FLOWER list </h1>

    {% if items %}
    <table class="table">
        <thead>
            <tr class="table-info">
                <th> # </th>
                <th> NAME </th>
                <th> INFO </th>
                <th> IMG </th>
                <th> KEYWORDS </th>
                <th> COLORS </th>
                <th> TYPES </th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <th> {{item.id}} </th>
                <td> {{item.name}}</td>
                <td> {{item.info}}</td>
                <td> <img src = "{{item.image.url}}" alt = "FLOWER_IMAGE" /> </td>
                <td> 
                    {% for keyword in item.tagged_keywords.all %}
                        {{ keyword.name }}<br>
                    {% endfor %}    
                </td>
                <td> 
                    {% for color in item.tagged_colors.all %}
                        {{ color.name }}<br>
                    {% endfor %}    
                </td>
                <td> 
                    {% for type in item.tagged_types.all %}
                        {{ type.name }}<br>
                    {% endfor %}    
                </td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    {% endif %}

{% endblock %}

posts/templates/posts/search.html
{% extends "base.html" %}
{% load static %}

{% block style %}
{% endblock %}

{% block content %}



<form action ="{% url 'posts:search_result' %}" method = "POST">
    {% csrf_token %}
    
    <p class="text-success"> *** KEYWORD 검색 부분 *** </p>
    {% for keyword in keywords %}
        <input type = "checkbox" name = "keyword_op" id = "{{keyword.name}}" value = "{{keyword.name}}">
        <label for = {{keyword.name}}> {{keyword.name}} </label>
    {% endfor %}

    <p class="text-success"> *** COLOR 검색 부분 *** </p>

    {% for flowercolor in flowercolors %}
    <input type = "checkbox" name = "flowercolor_op" id = "{{flowercolor.name}}" value = "{{flowercolor.name}}">
    <label for = {{flowercolor.name}}> {{flowercolor.name}} </label>
    {% endfor %}

    <p class="text-success"> *** TYPE 검색 부분 *** </p>
    {% for flowertype in flowertypes %}
    <input type = "checkbox" name = "flowertype_op" id = "{{flowertype.name}}" value = "{{flowertype.name}}">
    <label for = {{flowertype.name}}> {{flowertype.name}} </label>
    {% endfor %}</br>

    <input class="btn btn-outline-success p-3 px-md-5" type = "submit" value = "검색"/> 
</form>
    
{% endblock %}

posts/templates/posts/search_result.html
{% extends "base.html" %}
{% load static %}

{% block style %}
{% endblock %}

{% block content %}

<p> SEARCH RESULT</p>
<p> 1. KEYWORD 검색 항목: {{keyword_op}} </p>
<p> 2. COLOR 검색 항목: {{flowercolor_op}} </p>
<p> 3. TYPE 검색 항목: {{flowertype_op}} </p>




<div class="p-3 mb-2 bg-info text-white"> FLOWER LIST </div>
<div class="card-deck">
    {% for item in items %}

    <div class="card">
      <img src="{{item.image.url}}" class="card-img-top rounded" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{item.name}}</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FLOVER PROJECT</title>
    <link rel="stylesheet" href="{% static 'styles.css' %>" type = "text/css" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% block style %}
    {% endblock %}

    <div class="container border">

        <a href="{% url 'posts:index' %}">
            <button type="button" class="btn btn-outline-dark p-3 px-md-5">메인 페이지</button>
        </a>

        <a href="{% url 'posts:list_check' %}">
            <button type="button" class="btn btn-outline-dark p-3 px-md-5">상세 페이지</button>
        </a>

        <a href="{% url 'posts:search' %}">
          <button type="button" class="btn btn-outline-dark p-3 px-md-5">???</button>
        </a>

        <a href="{% url 'posts:search' %}">
          <button type="button" class="btn btn-outline-dark p-3 px-md-5">디자인 검색</button>
        </a>
      </div>
      
    </br>

    <div class="wrap">
      <div class="search">
         <input type="text" class="searchTerm" placeholder="What are you looking for?">
         <button type="submit" class="searchButton">
           <i class="fa fa-search"></i>
        </button>
      </div>
   </div>

   <style>
    @import url(https://fonts.googleapis.com/css?family=Open+Sans);

body{
 background: #f2f2f2;
 font-family: 'Open Sans', sans-serif;
}

.search {
 width: 100%;
 position: relative;
 display: flex;
}

.searchTerm {
 width: 100%;
 border: 3px solid #00B4CC;
 border-right: none;
 padding: 5px;
 height: 20px;
 border-radius: 5px 0 0 5px;
 outline: none;
 color: #9DBFAF;
}

.searchTerm:focus{
 color: #00B4CC;
}

.searchButton {
 width: 40px;
 height: 36px;
 border: 1px solid #00B4CC;
 background: #00B4CC;
 text-align: center;
 color: #fff;
 border-radius: 0 5px 5px 0;
 cursor: pointer;
 font-size: 20px;
}

/*Resize the wrap to see the search bar change!*/
.wrap{
 width: 30%;
 position: fixed;
 top: 0px;
 right: 200px;
 transform: translate(-50%, -50%);
}

  </style>

</head>
<body>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <P>BASE HTML의 마지막 부분</P>



    <footer>
        <p>Copyright © 2018 tcpschool.co.,Ltd. All rights reserved.</p>
        <address>Contact webmaster for more information. 070-1234-5678</address>
    </footer>


</body>
</html>